#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_EXPERT 1
#define CPTCFG_BP_MODULES 1
#define CPTCFG_DRM_I915_MODULE 1
#define CPTCFG_DRM_I915_FORCE_PROBE "*"
#define CPTCFG_DRM_I915_CAPTURE_ERROR 1
#define CPTCFG_DRM_I915_COMPRESS_ERROR 1
#define CPTCFG_DRM_I915_USERPTR 1
#define CPTCFG_DRM_I915_DEBUGGER 1
#define CPTCFG_DRM_I915_REQUEST_TIMEOUT 0
#define CPTCFG_DRM_I915_FENCE_TIMEOUT 10000
#define CPTCFG_DRM_I915_USERFAULT_AUTOSUSPEND 250
#define CPTCFG_DRM_I915_HEARTBEAT_INTERVAL 2500
#define CPTCFG_DRM_I915_PREEMPT_TIMEOUT 640
#define CPTCFG_DRM_I915_PREEMPT_TIMEOUT_COMPUTE 7500
#define CPTCFG_DRM_I915_PREEMPT_TIMEOUT_COMPUTE_COPY 2500
#define CPTCFG_DRM_I915_MAX_REQUEST_BUSYWAIT 8000
#define CPTCFG_DRM_I915_STOP_TIMEOUT 100
#define CPTCFG_DRM_I915_TIMESLICE_DURATION 1
#define CPTCFG_DRM_I915_DEBUGGER_KFIFO 256
#define CPTCFG_DRM_I915_CHICKEN_ASYNC_GET_PAGES 1
#define CPTCFG_DRM_I915_CHICKEN_PARALLEL_USERPTR 1
#define CPTCFG_DRM_I915_CHICKEN_CLEAR_ON_FREE 1
#define CPTCFG_DRM_I915_CHICKEN_CLEAR_ON_IDLE 1
#define CPTCFG_DRM_I915_CHICKEN_ULL_DMA_BOOST 1
#define CPTCFG_DRM_I915_CHICKEN_SOFT_PG 1
#define CPTCFG_INTEL_VSEC_MODULE 1
#define CPTCFG_WATCHDOG 1
#define CPTCFG_WATCHDOG_CORE_MODULE 1
#define CPTCFG_WATCHDOG_HANDLE_BOOT_ENABLED 1
#define CPTCFG_WATCHDOG_OPEN_TIMEOUT 0
#define CPTCFG_BACKPORTED_EXPERT 1
#define CPTCFG_BACKPORTED_BP_MODULES 1
#define CPTCFG_BACKPORTED_DRM_I915_MODULE 1
#define CPTCFG_BACKPORTED_DRM_I915_CAPTURE_ERROR 1
#define CPTCFG_BACKPORTED_DRM_I915_COMPRESS_ERROR 1
#define CPTCFG_BACKPORTED_DRM_I915_USERPTR 1
#define CPTCFG_BACKPORTED_DRM_I915_DEBUGGER 1
#define CPTCFG_BACKPORTED_DRM_I915_CHICKEN_ASYNC_GET_PAGES 1
#define CPTCFG_BACKPORTED_DRM_I915_CHICKEN_PARALLEL_USERPTR 1
#define CPTCFG_BACKPORTED_DRM_I915_CHICKEN_CLEAR_ON_FREE 1
#define CPTCFG_BACKPORTED_DRM_I915_CHICKEN_CLEAR_ON_IDLE 1
#define CPTCFG_BACKPORTED_DRM_I915_CHICKEN_ULL_DMA_BOOST 1
#define CPTCFG_BACKPORTED_DRM_I915_CHICKEN_SOFT_PG 1
#define CPTCFG_BACKPORTED_INTEL_VSEC_MODULE 1
#define CPTCFG_BACKPORTED_WATCHDOG 1
#define CPTCFG_BACKPORTED_WATCHDOG_CORE_MODULE 1
#define CPTCFG_BACKPORTED_WATCHDOG_HANDLE_BOOT_ENABLED 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
