# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2019, Intel Corporation. All rights reserved.
#
# Makefile - HDCP client driver for Intel MEI Bus Driver.

include $(BACKPORT_DIR)/.config
obj-$(CPTCFG_INTEL_MEI_HDCP) += mei_hdcp.o
